apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-cache
spec:
  template:
    spec:
      initContainers:
        - name: transfer-file-ownership
          image: us-central1-docker.pkg.dev/nelsona-sandbox/nelsona-dev-images/alpine-3.14:5.0.4
          command: ["sh", "-c", "chown -R 999:1000 /redis-data"]
          volumeMounts:
            - mountPath: /redis-data
              name: redis-data
          securityContext:
            runAsUser: 0
