apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    deploy: pod-tmp-gc
  name: pod-tmp-gc
spec:
  selector:
    matchLabels:
      app: pod-tmp-gc
  template:
    metadata:
      labels:
        app: pod-tmp-gc
      name: pod-tmp-gc
    spec:
      containers:
      - args:
        - $(NODE_NAME)
        - /pod-tmp
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        image: us-central1-docker.pkg.dev/nelsona-sandbox/nelsona-dev-images/pod-tmp-gc:5.0.4
        terminationMessagePolicy: FallbackToLogsOnError
        name: pod-tmp-gc
        resources:
          limits:
            cpu: 10m
            memory: 20M
        # Replace ${SSD_NODE_PATH} with the absolute directory path 
        # on the node where the local SSD is mounted.
        # See ../README.md for more information.
        volumeMounts:
        - name: pod-tmp
          mountPath: $(SSD_NODE_PATH)
          subPathExpr: pod-tmp
      serviceAccountName: pod-tmp-gc
  updateStrategy: {}
