apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: gitserver
spec:
  template:
    spec:
      initContainers:
        - name: transfer-file-ownership
          image: us-central1-docker.pkg.dev/nelsona-sandbox/nelsona-dev-images/alpine-3.14:5.0.4
          command:
            [
              "sh",
              "-c",
              'if [[ "$(stat -c ''%u'' /data/repos)" -ne 100 ]]; then chown -R 100:101 /data/repos; fi',
            ]
          volumeMounts:
            - mountPath: /data/repos
              name: repos
          securityContext:
            runAsUser: 0
