apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
spec:
  template:
    spec:
      initContainers:
        - name: transfer-file-ownership
          image: us-central1-docker.pkg.dev/nelsona-sandbox/nelsona-dev-images/alpine-3.14:5.0.4
          command: ["sh", "-c", "chown -R 100:100 /prometheus"]
          volumeMounts:
            - mountPath: /prometheus
              name: data
          securityContext:
            runAsUser: 0
